Resources:
  LeadsTable: # Nome lógico - Serve só para identificar o recurso no SLS
    Type: AWS::DynamoDB::Table # Recurso - CloudFormation
    Properties:
      TableName: live-039-leads-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema: # Define as PK/SK
        - AttributeName: id
          KeyType: HASH # HASH -> Partition Key
